### ISSUE TITLE
Switching between builds and pickaxe crashes the server.

### ISSUE THREAD

**Issue by max8447** [GDBOI101/WaybackGS#3]
Okay, so I was in the pre-game lobby and switched from the pickaxe to my builds and back quite quickly, and that crashed the server lmao. Oh and btw the game doesn't start does it?

**Comment by kumail12345** [comment]
yo what backend do u use please tell me my user on discord is Pakislamic#0713 max8447 please respond bye,

**Comment by max8447** [comment]
i sent u a friend request

**Comment by max8447** [comment]
okay nevermind, this is the error i'm getting, and i think it happens randomly when switching from the builds to the pickaxe:
LogWindows:Error: === Critical error: ===
LogWindows:Error:
LogWindows:Error: Fatal error!
LogWindows:Error:
LogWindows:Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x00000029
LogWindows:Error:
LogWindows:Error: 0x000000002977962A
LogWindows:Error: 0x0000000076726553
LogWindows:Error: 0x0000000074634179
LogWindows:Error: 0x0000000069624165
LogWindows:Error: 0x000000008B98C900
LogWindows:Error: 0x000000008B98C900
LogWindows:Error:

**Comment by GDBOI101** [comment]
Ik It's an issue that I still haven't found out what causes it

**Comment by max8447** [comment]
well what i think causes it is if you're trying to build somewhere where it's being blocked by lets say a tree, and then switch to pickaxe (that's the only 2 times it has happened to me but im boutta test it)

**Comment by GDBOI101** [comment]
Fixed it. I will push when I finish some other stuff
