### ISSUE TITLE
stuff need to fix

### ISSUE THREAD

**Issue by Project-Z1K** [GDBOI101/WaybackGS#6]
# shits u need to code xd

"Crash 100% on MCP, and if you remove the MCP code, it should work, but now it just crashes.
Floor loot doesn't work.
laggy asf.
Looting is subpar.
Editing is subpar.
Building is subpar.
When you kill a player, you don't get loot.
Spectating doesn't work; you're so buggy.
Late-game zones don't work (I already fixed this; it's easy).
Harvesting needs a v 2."

# and prob need to recode hold source bc is laggy asfff

**Comment by GDBOI101** [comment]
Pushed fixes please stop dming me :/
