### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Project-Z1K** [GDBOI101/WaybackGS#7]
indect the gs and crash lol
![image](https://github.com/GDBOI101/WaybackGS/assets/149071205/5fa3828f-51a1-459c-a76c-eae586d00173)

**Comment by GDBOI101** [comment]
Are you injecting in the lobby? I have 0 issues when launching and I've had several people test and theirs worked fine too.

**Comment by GDBOI101** [comment]
Headless servers don't work.
